version: '3'
services:
  db:
    image: postgres
  web: 
    build: ./rails-2.6.3
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/workspace
    ports:
      - 3000:3000
    depends_on:
      - db
